### ISSUE TITLE
Dual mode failing due to missing single quote

### ISSUE THREAD

**Issue by olivertam** [bvaldebenitom/SoloTE#46]
Hi,

Thank you for developing this software.
I have been trying out the dual mode, and noticed that it's throwing this error:
```bash
sh: -c: line 0: unexpected EOF while looking for matching `''
sh: -c: line 1: syntax error: unexpected end of file
```
As a result, it crashes because it can't open a BAM file:
```
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=samtools idxstats: failed to open "final.bam": No such file or directory\n'
```
I dug into the code, and found that line 137 in the SoloTE_pipeline.py might be missing a quote (after the -e portion).
``` python
cmd="samtools view -@ "+cpus+" -O BAM -o "+te_bam+" -L "+TE_bed+" -e '(exists([CB]) && exists([UB]) && [CB]!=\"-\" && [UB]!=\"-\") "+inputbam
```
I wonder if this fix could resolve it:
``` python
cmd="samtools view -@ "+cpus+" -O BAM -o "+te_bam+" -L "+TE_bed+" -e '(exists([CB]) && exists([UB]) && [CB]!=\"-\" && [UB]!=\"-\")' "+inputbam
```

Also, I have been getting this syntax warning message (I'm using python 3.12.3):
``` python
SoloTE_pipeline.py:231: SyntaxWarning: invalid escape sequence '\?'
  te_final_df.replace("\?","",inplace=True,regex=True)
SoloTE_pipeline.py:232: SyntaxWarning: invalid escape sequence '\|'
  locus_tes = te_final_df[te_final_df['TE_original_id'].str.contains("SoloTE\|chr")]
```
I wonder if it's because you need to have double backslashes (`\\`) to make the escape sequence:
``` python
  te_final_df.replace("\\?","",inplace=True,regex=True)
  locus_tes = te_final_df[te_final_df['TE_original_id'].str.contains("SoloTE\\|chr")]
```

Apologies for the numerous questions.

Thanks.

**Comment by bvaldebenitom** [comment]
Hi @olivertam !

It's nice to greet you again. And don't worry for the amount of questions. Your feedback is always very constructive.

- Regarding the dual mode, there is indeed a missing single quote. This is now fixed in the latest commit, and this is available on GitHub. I'm working in other bug fixes and once that's done, I'll make a new formal release. 

Based on your comment, I assume that you have already made the change in your copy of the code, so you probably don't need to download / clone the new files. Anyhow, the fixed version is now available for provenance and for future users interested in using this mode.

- I installed and tested Python version 3.12.3, and the escape sequence behavior seems to have changed, compared to Python 3.9. In the [changelog for 3.12](https://docs.python.org/3/whatsnew/3.12.html#other-language-changes), there is indeed a mention to this:

> A backslash-character pair that is not a valid escape sequence now generates a [SyntaxWarning](https://docs.python.org/3/library/exceptions.html#SyntaxWarning), instead of [DeprecationWarning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning). For example, re.compile("\d+\.\d+") now emits a [SyntaxWarning](https://docs.python.org/3/library/exceptions.html#SyntaxWarning) ("\d" is an invalid escape sequence, use raw strings for regular expression: re.compile(r"\d+\.\d+")). In a future Python version, [SyntaxError](https://docs.python.org/3/library/exceptions.html#SyntaxError) will eventually be raised, instead of [SyntaxWarning](https://docs.python.org/3/library/exceptions.html#SyntaxWarning).

Since for now this is only a warning, is not a big cause of concern. Though I will update this to avoid errors when a new version of Python eventually switches to that behavior.

Let me know if you have further comments.

**Comment by olivertam** [comment]
Thanks for the prompt responses!

All the best!
