### ISSUE TITLE
Probe-based scRNA sequencing

### ISSUE THREAD

**Issue by blaverty** [bvaldebenitom/SoloTE#51]
Hi! Thanks so much for your tool!

I see in your paper the 3 datasets you applied SoloTE to used 3' scRNA sequencing or bulk RNA sequencing. Can this tool be applied to scRNA seq using the Chromium platform with probe-based sequencing?

**Comment by bvaldebenitom** [comment]
Hi @blaverty !

With "probe-based" sequencing are you referring to the 10X "Chromium Single Cell Gene Expression Flex" protocol? If so, I can take a look. In theory, if the BAM file is generated with the CB and UB tags, SoloTE should work. 

I will run some tests, and let you know.

**Comment by blaverty** [comment]
Yes that is what I'm referring to. Thank you for checking, I appreciate it!

**Comment by bvaldebenitom** [comment]
Hi @blaverty !

I ran some tests on data available at the 10X Genomics, and SoloTE will work. However, since it is probe-based, it targets mainly genes. 

You can try running it with the `--dual` flag, as it will allow counts from gene to also be used in TE expression. However, I only noticed that I got 0.2% of TE expression without it, and increased it to 0.3% when using the flag.
