### ISSUE TITLE
SoloTE-locus/SoloTE-family

### ISSUE THREAD

**Issue by balazspalhazi** [bvaldebenitom/SoloTE#55]
legacytes_MATRIX: Results summarized at the locus level for uniquely mapped reads, and at the subfamily level for multi-mapped reads. This was the default output until v1.08, and the one used in the publication.

Dear bvaldebenitom,

last year, we performed the SoloTE analysis using version v1.04 or v1.05. I would like to kindly ask for clarification regarding the "SoloTE-Family name" TE indicated in the SoloTE results. Does this refer to the entire family across all mapped loci?

I am waiting for your reply,

Best,

Balazs

**Comment by Bathroomboss** [comment]
Dear bvaldebenitom,

I would like to ask here, what do the 5 result directories represent respectively? 

I read the paper but I can't find. If I missed it, could you please tell me where I can find it?

Best,

Yu

**Comment by bvaldebenitom** [comment]
Hi @balazspalhazi and @Bathroomboss ,

thanks for the questions. From version 1.09, there are new outputs generated. This was done in order to provide a seamless generation of the matrices corresponding to different ways of analyzing TE data. The description for each one is as follows:

- `classtes_MATRIX`: Matrix contains TE expression summarized at the class level (LTR, LINE, SINE, DNA).
- `familytes_MATRIX`: Matrix with TE expression summarized at the family level.
- `subfamilytes_MATRIX`: Matrix with TE expression summarized at the subfamily level.
- `locustes_MATRIX`: Matrix containing TE expression at the locus level (using only uniquely mapped reads).
- `legacytes_MATRIX`: Matrix containing TE expression at the locus level (again, using only uniquely mapped reads), and at the subfamily level for reads not mapping uniquely.

Overall the class, family, and subfamily matrices could be used to get an idea of global changes in TE expression. For example, the tool scTE reports results only at the subfamily level, and here we provide users with a similar output. On the other hand, `locustes` and `legacytes` matrices contain locus-specific expression which might be helpful for correlation analyses. A more detailed explanation of the difference between locus and legacy can be found [here](https://github.com/bvaldebenitom/SoloTE/issues/30#issuecomment-1721876808). Previously, the default (and only output) was the legacy TEs.

@balazspalhazi , to answer your question, yes, family TEs has all the counts aggregated across all loci.

Please let me know if this is helpful.

**Comment by Bathroomboss** [comment]
> Hi @balazspalhazi and @Bathroomboss ,
> 
> thanks for the questions. From version 1.09, there are new outputs generated. This was done in order to provide a seamless generation of the matrices corresponding to different ways of analyzing TE data. The description for each one is as follows:
> 
> * `classtes_MATRIX`: Matrix contains TE expression summarized at the class level (LTR, LINE, SINE, DNA).
> * `familytes_MATRIX`: Matrix with TE expression summarized at the family level.
> * `subfamilytes_MATRIX`: Matrix with TE expression summarized at the subfamily level.
> * `locustes_MATRIX`: Matrix containing TE expression at the locus level (using only uniquely mapped reads).
> * `legacytes_MATRIX`: Matrix containing TE expression at the locus level (again, using only uniquely mapped reads), and at the subfamily level for reads not mapping uniquely.
> 
> Overall the class, family, and subfamily matrices could be used to get an idea of global changes in TE expression. For example, the tool scTE reports results only at the subfamily level, and here we provide users with a similar output. On the other hand, `locustes` and `legacytes` matrices contain locus-specific expression which might be helpful for correlation analyses. A more detailed explanation of the difference between locus and legacy can be found [here](https://github.com/bvaldebenitom/SoloTE/issues/30#issuecomment-1721876808). Previously, the default (and only output) was the legacy TEs.
> 
> @balazspalhazi , to answer your question, yes, family TEs has all the counts aggregated across all loci.
> 
> Please let me know if this is helpful.

Thanks for your quick reply and developing SoloTE, it may be a great help to me.  I will try to use it.
